//////////////AUTHORIZATION CONSTANTS//////////////////////
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const IS_LOGGED_OUT = 'IS_LOGGED_OUT';
export const GET_GRAPH_DATA = 'GET_GRAPH_DATA';
export const GET_ORDER_DATA = 'GET_ORDER_DATA';
export const GET_ORDER_DATA_COUNT = 'GET_ORDER_DATA_COUNT';
export const GET_DELIVERY_AMOUNT_DATA = 'GET_DELIVERY_AMOUNT_DATA';
export const GET_SKU_DATA = 'GET_SKU_DATA';
export const GET_DELIVERY_AMOUNT_BY_DRIVER_DATA = 'GET_DELIVERY_AMOUNT_BY_DRIVER_DATA';
export const GET_QUERY_NET_DATA = 'GET_QUERY_NET_DATA';
export const GET_GROSS_SALES_DATA = 'GET_GROSS_SALES_DATA';
export const GET_DELIVERY_AMOUNT_BY_DISTRIBUTOR = 'GET_DELIVERY_AMOUNT_BY_DISTRIBUTOR';
export const GET_DELIVERED_ORDERS_BY_DRIVER = 'GET_DELIVERED_ORDERS_BY_DRIVER';
export const GET_QUERY_AVERAGE_SALES = 'GET_QUERY_AVERAGE_SALES';
export const GET_DRIVER_DELIVERY_AMOUNT_DATA = 'GET_DRIVER_DELIVERY_AMOUNT_DATA';
export const GET_TOP_SKUS = 'GET_TOP_SKUS';
export const GET_TOP_STORES = 'GET_TOP_STORES';
export const GET_NUMERICAL_DISTRIBUTION = 'GET_NUMERICAL_DISTRIBUTION';
export const GET_DAILY_SHIPPING_STATUS = 'GET_DAILY_SHIPPING_STATUS';
export const GET_DAILY_ACTIVE_STORES = 'GET_DAILY_ACTIVE_STORES';
export const GET_AVERAGE_ORDERS = 'GET_AVERAGE_ORDERS';
export const GET_DELIVERY_RATE = 'GET_DELIVERY_RATE';
export const GET_DAILY_DELIVERY = 'GET_DAILY_DELIVERY';
export const GET_CANCEL_REASONS = 'GET_CANCEL_REASONS';



